version: '3.9'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb-compose
    environment:
      MYSQL_ROOT_PASSWORD: bill1234 
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306" 
    networks:
      - mariadb_network

networks:
  mariadb_network:
    driver: bridge
